// styles
import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";

// types & interfaces
import type { Metadata } from "next";

// 3rd party libraries
import { Inter } from "next/font/google";
import { Theme } from "@radix-ui/themes";

// internal imports
import NavBar from "./NavBar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Theme appearance="light" accentColor="purple">
          <NavBar />
          <main className="p-5">{children}</main>
        </Theme>
      </body>
    </html>
  );
}
